### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by akafazov** [Daiteap/daiteapcli#4]
This is a placeholder for various findings/bugs which will be later created as separate issues.

List:
- [x] command `projects [NAME] get` to return a list of all resources/contents of a project
- [x] add config command which can display and change the target API endpoint for making requests
- [x] add `debug` or `verbose` flag, so that the actual HTTP response can be printed 
- [x] improve error handling by printing the error MSG, not only the HTTP response code
- [x] add `--dry-run` flag to generate request headers and payload, without actually sending it to the API
- [x] creating **aws** cloud-credential fails
```shell
daiteapcli cloud-credentials create --aws-access-key-id ACCESS_KEY_D \
--aws-secret-access-key ACCESS_KEY\
 --label aws-credentials1 \
--description "Description" \
--shared-credentials false \
--provider aws
invalid Status code (400)
```
- [x] add colors to output
- [x] `project create` **--description** flag is required but should be optional
- [x] flags/parameters not documented if optional/required
- [x] add "wide" output option to list commands
- [x] add logout command
- [x] give one-letter shorthand for "output" flag
- [x] rework "k8s create-dlcmv2" to "k8s create --lcm=dlcmv2"
- [x] assign default server URL config if none is present
- [x] add aliases for "environment-template", "service-catalog" and "cloud-credentials" commands
- [x] support local deployment of daiteap-platform (no tokey/keycloak needed)

**Comment by bpavlov-daiteap** [comment]
Add `verbose` flag
Improve error handling by adding `verbose` flag
Add `dry-run` flag
Add `logout` command
Add default server URL config if none is present
All optional flags are specified in their description
Fix for missing config parent directory missing
